import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { ApiError } from '../api/client'
import { PageHeader } from '../components/PageHeader'
import { listCustomers, updateCustomerStatus } from '../operations/operationsService'
import type { Customer, Pagination } from '../operations/types'
const initial: Pagination = { total: 0, per_page: 20, current_page: 1, last_page: 1 }
export function CustomersPage() {
  const [customers, setCustomers] = useState<Customer[]>([]); const [pagination, setPagination] = useState(initial); const [page, setPage] = useState(1); const [searchInput, setSearchInput] = useState(''); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await listCustomers({ page, per_page: 20, search, status, sort: 'newest' }); setCustomers(response.data); setPagination(response.meta.pagination ?? initial) } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Customers could not be loaded.') } finally { setLoading(false) } }, [page, search, status])
  // oxlint-disable-next-line react/set-state-in-effect
  useEffect(() => { void load() }, [load])
  function submit(event: FormEvent) { event.preventDefault(); setPage(1); setSearch(searchInput.trim()) }
  async function toggle(customer: Customer) { try { await updateCustomerStatus(customer.public_id, customer.status === 'active' ? 'disabled' : 'active'); await load() } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Customer status could not be updated.') } }
  return <div className="space-y-6"><PageHeader title="Customers" description="Review customer activity and control account access." /><section className="rounded-xl border border-stone-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row"><form className="flex flex-1 gap-2" onSubmit={submit}><input className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm" value={searchInput} onChange={(event) => setSearchInput(event.target.value)} placeholder="Search name, email, or phone" /><button className="rounded-lg border px-4 text-sm">Search</button></form><select className="rounded-lg border px-3 py-2 text-sm" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1) }}><option value="">All statuses</option><option value="active">Active</option><option value="disabled">Disabled</option></select></div>{error ? <div className="p-10 text-center text-sm text-red-700">{error}</div> : loading ? <div className="p-12 text-center text-sm text-stone-500">Loading customers…</div> : <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-stone-50 text-xs uppercase text-stone-500"><tr><th className="p-3">Customer</th><th>Phone</th><th>Orders</th><th>Paid spend</th><th>Joined</th><th>Status</th><th /></tr></thead><tbody className="divide-y">{customers.map((customer) => <tr key={customer.public_id}><td className="p-3"><p className="font-medium">{customer.name}</p><p className="text-xs text-stone-500">{customer.email ?? 'No email'}</p></td><td>{customer.phone ?? '—'}</td><td>{customer.orders_count}</td><td>{new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(customer.total_spent)}</td><td>{new Date(customer.created_at).toLocaleDateString('id-ID')}</td><td><span className={`rounded-full px-2 py-1 text-xs ${customer.status === 'active' ? 'bg-emerald-100 text-emerald-800' : 'bg-stone-200 text-stone-700'}`}>{customer.status}</span></td><td className="pr-3 text-right"><button className="rounded border px-3 py-1 text-xs" onClick={() => void toggle(customer)}>{customer.status === 'active' ? 'Disable' : 'Activate'}</button></td></tr>)}</tbody></table>{customers.length === 0 && <div className="p-12 text-center text-sm text-stone-500">No customers found.</div>}</div>}<div className="flex justify-between border-t p-3 text-sm"><span>{pagination.total} customers · Page {pagination.current_page} of {pagination.last_page}</span><div className="flex gap-2"><button disabled={page <= 1} className="rounded border px-3 py-1 disabled:opacity-40" onClick={() => setPage(page - 1)}>Previous</button><button disabled={page >= pagination.last_page} className="rounded border px-3 py-1 disabled:opacity-40" onClick={() => setPage(page + 1)}>Next</button></div></div></section></div>
}
