import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { ApiError } from '../api/client'
import { PageHeader } from '../components/PageHeader'
import { adjustInventory, getInventoryMovements, getVariantInventory } from '../inventory/inventoryService'
import type { InventoryLevel, InventoryMovement } from '../inventory/types'

const control = 'w-full rounded-lg border border-stone-300 bg-white px-3 py-2 text-sm'
export function InventoryDetailPage({ variantId }: { variantId: string }) {
  const query = new URLSearchParams(location.search); const productName = query.get('product') ?? 'Product'; const variantName = query.get('variant') ?? variantId; const sku = query.get('sku')
  const [levels, setLevels] = useState<InventoryLevel[]>([]); const [movements, setMovements] = useState<InventoryMovement[]>([]); const [pagination, setPagination] = useState({ total: 0, current_page: 1, last_page: 1 })
  const [page, setPage] = useState(1); const [sort, setSort] = useState('newest'); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState(false)
  const [form, setForm] = useState({ location_code: 'MAIN', quantity_delta: '', reason: '', reference_type: '', reference_id: '' })
  const load = useCallback(async () => { try { const [inventory, history] = await Promise.all([getVariantInventory(variantId), getInventoryMovements(variantId, { page, per_page: 20, sort })]); setLevels(inventory.data); setMovements(history.data); setPagination({ total: history.meta.pagination.total, current_page: history.meta.pagination.current_page, last_page: history.meta.pagination.last_page }); setError(null) } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Inventory could not be loaded.') } }, [page, sort, variantId])
  // oxlint-disable-next-line react/set-state-in-effect
  useEffect(() => { void load() }, [load])
  const activeLevel = levels.find((level) => level.location.code === form.location_code)
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError(null)
    try { await adjustInventory(variantId, { location_code: form.location_code, quantity_delta: Number(form.quantity_delta), reason: form.reason, reference_type: form.reference_type || null, reference_id: form.reference_id || null, expected_version: activeLevel?.version ?? 0 }); setNotice('Inventory adjustment recorded successfully.'); setForm({ ...form, quantity_delta: '', reason: '', reference_type: '', reference_id: '' }); setPage(1); await load() } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Adjustment could not be recorded.') } finally { setBusy(false) }
  }
  return <div className="space-y-6"><div className="flex items-end justify-between"><PageHeader title={`${variantName} inventory`} description={`${productName}${sku ? ` · ${sku}` : ''}`} /><a href="/inventory" className="rounded-lg border px-4 py-2 text-sm">Back to inventory</a></div>
    {error && <div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}{notice && <div className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}
    <div className="grid gap-5 lg:grid-cols-3"><section className="rounded-xl border bg-white p-5 lg:col-span-2"><h2 className="font-semibold">Inventory levels</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{levels.map((level) => <article key={level.location.code} className="rounded-lg border p-4"><div className="flex justify-between"><div><h3 className="font-medium">{level.location.name}</h3><code className="text-xs text-stone-500">{level.location.code}</code></div><span className="text-xs text-stone-500">Version {level.version}</span></div><dl className="mt-4 grid grid-cols-2 gap-3"><div><dt className="text-xs text-stone-500">On hand</dt><dd className="text-xl font-semibold">{level.on_hand}</dd></div><div><dt className="text-xs text-stone-500">Reserved</dt><dd className="text-xl">{level.reserved}</dd></div><div><dt className="text-xs text-stone-500">Safety stock</dt><dd className="text-xl">{level.safety_stock}</dd></div><div><dt className="text-xs text-stone-500">Available</dt><dd className="text-xl font-semibold text-emerald-700">{level.available}</dd></div></dl></article>)}{!levels.length && <p className="text-sm text-stone-500">MAIN inventory has not been initialized. The first adjustment will create it.</p>}</div></section>
      <form className="rounded-xl border bg-white p-5" onSubmit={submit}><h2 className="font-semibold">Stock adjustment</h2><div className="mt-4 space-y-3"><label className="block text-sm">Location<select className={`${control} mt-1`} value={form.location_code} onChange={(event) => setForm({ ...form, location_code: event.target.value })}>{levels.length ? levels.filter((level) => level.location.is_active).map((level) => <option key={level.location.code} value={level.location.code}>{level.location.name}</option>) : <option value="MAIN">MAIN</option>}</select></label><label className="block text-sm">Quantity delta<input required className={`${control} mt-1`} type="number" step="1" placeholder="+20 or -5" value={form.quantity_delta} onChange={(event) => setForm({ ...form, quantity_delta: event.target.value })} /></label><label className="block text-sm">Reason<textarea required className={`${control} mt-1`} maxLength={500} value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} /></label><label className="block text-sm">Reference type<input className={`${control} mt-1`} placeholder="purchase_order" value={form.reference_type} onChange={(event) => setForm({ ...form, reference_type: event.target.value })} /></label><label className="block text-sm">Reference ID<input className={`${control} mt-1`} placeholder="PO-2026-0916" value={form.reference_id} onChange={(event) => setForm({ ...form, reference_id: event.target.value })} /></label><button disabled={busy} className="w-full rounded-lg bg-stone-900 px-4 py-2 text-sm text-white disabled:opacity-50">{busy ? 'Saving…' : 'Record adjustment'}</button></div></form></div>
    <section className="rounded-xl border bg-white"><div className="flex items-center justify-between border-b p-5"><h2 className="font-semibold">Movement history</h2><select className={control} value={sort} onChange={(event) => { setSort(event.target.value); setPage(1) }}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-stone-50 text-xs uppercase text-stone-500"><tr><th className="p-3">Date</th><th>Type</th><th>Quantity change</th><th>Reason</th><th>Reference</th><th>Actor</th></tr></thead><tbody className="divide-y">{movements.map((movement, index) => <tr key={`${movement.created_at}-${index}`}><td className="p-3">{new Date(movement.created_at).toLocaleString()}</td><td className="capitalize">{movement.movement_type}</td><td className={movement.quantity_delta > 0 ? 'text-emerald-700' : 'text-red-700'}>{movement.quantity_delta > 0 ? '+' : ''}{movement.quantity_delta}</td><td>{movement.reason ?? '—'}</td><td>{movement.reference_type && movement.reference_id ? `${movement.reference_type}: ${movement.reference_id}` : '—'}</td><td>{movement.actor?.name ?? 'System'}</td></tr>)}</tbody></table>{!movements.length && <div className="p-10 text-center text-sm text-stone-500">No inventory movements recorded.</div>}</div><div className="flex justify-between border-t p-3 text-sm"><span>{pagination.total} movements · Page {pagination.current_page} of {pagination.last_page}</span><div className="flex gap-2"><button disabled={page <= 1} className="rounded border px-3 py-1 disabled:opacity-40" onClick={() => setPage(page - 1)}>Previous</button><button disabled={page >= pagination.last_page} className="rounded border px-3 py-1 disabled:opacity-40" onClick={() => setPage(page + 1)}>Next</button></div></div></section>
  </div>
}
