import { useCallback, useEffect, useState } from 'react'
import { ApiError } from '../api/client'
import { PageHeader } from '../components/PageHeader'
import { OrderStatusBadge } from '../orders/OrderStatusBadge'
import { getOrder, updateOrderStatus } from '../orders/orderService'
import type { AddressSnapshot, OrderDetail, OrderStatus } from '../orders/types'
const transitions: Record<OrderStatus, OrderStatus[]> = { pending: ['processing', 'cancelled'], processing: ['shipped', 'cancelled'], shipped: ['completed'], completed: [], cancelled: [] }
function money(amount: number, currency: string) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency, maximumFractionDigits: currency === 'IDR' ? 0 : 2 }).format(currency === 'IDR' ? amount : amount / 100) }
function Address({ title, address }: { title: string; address: AddressSnapshot }) { return <div><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-stone-600">{address.recipient_name}<br />{address.line1}{address.line2 ? <><br />{address.line2}</> : null}<br />{address.city}{address.province ? `, ${address.province}` : ''} {address.postal_code}<br />{address.country_code}</p></div> }
export function OrderDetailPage({ publicId }: { publicId: string }) {
  const [order, setOrder] = useState<OrderDetail | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [selected, setSelected] = useState<OrderStatus | ''>(''); const [confirming, setConfirming] = useState(false); const [saving, setSaving] = useState(false)
  const load = useCallback(async () => { setLoading(true); setError(null); try { setOrder((await getOrder(publicId)).data) } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Order could not be loaded.') } finally { setLoading(false) } }, [publicId])
  // oxlint-disable-next-line react/set-state-in-effect
  useEffect(() => { void load() }, [load])
  async function update() { if (!selected) return; setSaving(true); setError(null); try { const response = await updateOrderStatus(publicId, selected); setOrder(response.data); setNotice(`Order status updated to ${selected}.`); setSelected(''); setConfirming(false) } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Order status could not be updated.'); setConfirming(false) } finally { setSaving(false) } }
  if (loading) return <div className="p-12 text-center text-sm text-stone-500">Loading order…</div>
  if (error && !order) return <div className="p-12 text-center text-sm text-red-700">{error} <button className="underline" onClick={() => void load()}>Try again</button></div>
  if (!order) return null
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><PageHeader title={order.order_number} description={`Created ${new Date(order.created_at).toLocaleString()}`} /><OrderStatusBadge status={order.status} /></div>{notice && <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}{error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)]"><div className="space-y-6"><section className="rounded-xl border bg-white"><h2 className="border-b p-5 text-lg font-semibold">Items</h2><div className="divide-y">{order.items.map((item) => <div key={item.sku} className="grid grid-cols-[1fr_auto] gap-4 p-5 text-sm"><div><p className="font-medium">{item.product_name}</p><p className="text-stone-500">{item.variant_name ?? item.sku} · {item.sku}</p><p className="mt-1 text-xs text-stone-500">Qty {item.quantity} × {money(item.unit_price_amount, item.currency)}</p></div><span>{money(item.total_amount, item.currency)}</span></div>)}</div><dl className="ml-auto grid max-w-sm gap-2 border-t p-5 text-sm"><div className="flex justify-between"><dt>Subtotal</dt><dd>{money(order.subtotal_amount, order.currency)}</dd></div><div className="flex justify-between"><dt>Discount</dt><dd>{money(order.discount_amount, order.currency)}</dd></div><div className="flex justify-between"><dt>Shipping</dt><dd>{money(order.shipping_amount, order.currency)}</dd></div><div className="flex justify-between"><dt>Tax</dt><dd>{money(order.tax_amount, order.currency)}</dd></div><div className="flex justify-between border-t pt-2 font-semibold"><dt>Total</dt><dd>{money(order.grand_total_amount, order.currency)}</dd></div></dl></section><section className="grid gap-6 rounded-xl border bg-white p-5 md:grid-cols-2"><Address title="Shipping address" address={order.shipping_address} /><Address title="Billing address" address={order.billing_address} /></section></div>
      <aside className="space-y-6"><section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Customer</h2><p className="mt-3 text-sm">{order.customer.name}</p><p className="text-sm text-stone-500">{order.customer.email}<br />{order.customer.phone}</p></section><section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Payment</h2><div className="mt-3"><OrderStatusBadge status={order.payment.status} /></div>{order.payment.provider ? <dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between"><dt className="text-stone-500">Provider</dt><dd className="capitalize">{order.payment.provider}</dd></div><div className="flex justify-between"><dt className="text-stone-500">Method</dt><dd className="capitalize">{order.payment.method_type}</dd></div><div className="flex justify-between"><dt className="text-stone-500">Amount</dt><dd>{order.payment.amount === null ? '—' : money(order.payment.amount, order.payment.currency)}</dd></div><div><dt className="text-stone-500">Provider reference</dt><dd className="mt-1 break-all">{order.payment.provider_reference ?? '—'}</dd></div><div><dt className="text-stone-500">Paid at</dt><dd>{order.payment.paid_at ? new Date(order.payment.paid_at).toLocaleString() : '—'}</dd></div></dl> : <p className="mt-2 text-xs text-stone-500">No payment has been created.</p>}</section><section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Update status</h2>{transitions[order.status].length ? <><select className="mt-3 w-full rounded-lg border p-2 text-sm" value={selected} onChange={(e) => setSelected(e.target.value as OrderStatus)}><option value="">Select next status</option>{transitions[order.status].map((status) => <option key={status}>{status}</option>)}</select><button disabled={!selected} className="mt-3 w-full rounded-lg bg-stone-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-40" onClick={() => setConfirming(true)}>Update status</button></> : <p className="mt-2 text-sm text-stone-500">This order has reached a final status.</p>}</section><section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Status timeline</h2><ol className="mt-4 space-y-4 border-l pl-4">{order.status_history.map((event, index) => <li key={`${event.changed_at}-${index}`}><p className="text-sm font-medium capitalize">{event.to}</p><p className="text-xs text-stone-500">{new Date(event.changed_at).toLocaleString()}{event.actor ? ` · ${event.actor.name}` : ''}</p></li>)}</ol></section></aside></div>
    {confirming && selected && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="w-full max-w-md rounded-xl bg-white p-6"><h2 className="text-lg font-semibold">Update order status?</h2><p className="mt-2 text-sm text-stone-600">Move {order.order_number} from <strong>{order.status}</strong> to <strong>{selected}</strong>?{selected === 'cancelled' ? ' Reserved inventory will be released.' : ''}</p><div className="mt-5 flex justify-end gap-2"><button className="rounded border px-4 py-2" onClick={() => setConfirming(false)}>Keep current status</button><button disabled={saving} className="rounded bg-stone-900 px-4 py-2 text-white disabled:opacity-50" onClick={() => void update()}>{saving ? 'Updating…' : 'Confirm update'}</button></div></div></div>}
  </div>
}
