import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { ApiError } from '../api/client'
import { PageHeader } from '../components/PageHeader'
import { deleteProductMedia, listProductMedia, updateProductMedia, uploadProductMedia } from '../media/mediaService'
import type { ProductMedia } from '../media/types'
import { getProduct } from '../products/productService'
import type { Product } from '../products/types'

const control = 'w-full rounded-lg border border-stone-300 bg-white px-3 py-2 text-sm'
function message(error: unknown): string { return error instanceof ApiError ? error.errors.map((item) => item.message).filter(Boolean).join(' ') || error.message : 'The request could not be completed.' }

export function ProductMediaPage({ publicId }: { publicId: string }) {
  const [product, setProduct] = useState<Product | null>(null); const [images, setImages] = useState<ProductMedia[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [progress, setProgress] = useState<number | null>(null)
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<string | null>(null); const [upload, setUpload] = useState({ alt_text: '', variant_public_id: '', is_primary: false })
  const load = useCallback(async () => { setLoading(true); try { const [productResponse, mediaResponse] = await Promise.all([getProduct(publicId), listProductMedia(publicId)]); setProduct(productResponse.data); setImages(mediaResponse.data); setError(null) } catch (caught) { setError(message(caught)) } finally { setLoading(false) } }, [publicId])
  // oxlint-disable-next-line react/set-state-in-effect
  useEffect(() => { void load() }, [load])
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview) }, [preview])
  function selectFile(selected: File | null) { if (preview) URL.revokeObjectURL(preview); setFile(selected); setPreview(selected ? URL.createObjectURL(selected) : null) }
  async function submit(event: FormEvent) {
    event.preventDefault(); if (!file) return; setError(null); setProgress(0)
    const data = new FormData(); data.append('image', file); data.append('alt_text', upload.alt_text); data.append('is_primary', upload.is_primary ? '1' : '0'); if (upload.variant_public_id) data.append('variant_public_id', upload.variant_public_id)
    try { await uploadProductMedia(publicId, data, setProgress); setNotice('Image uploaded successfully.'); selectFile(null); setUpload({ alt_text: '', variant_public_id: '', is_primary: false }); await load() } catch (caught) { setError(message(caught)) } finally { setProgress(null) }
  }
  async function update(image: ProductMedia, changes: Partial<ProductMedia>, success: string) { setBusy(image.public_id); setError(null); try { await updateProductMedia(publicId, image.public_id, changes); setNotice(success); await load() } catch (caught) { setError(message(caught)) } finally { setBusy(null) } }
  async function remove(image: ProductMedia) { if (!confirm('Delete this image permanently from product media?')) return; setBusy(image.public_id); try { await deleteProductMedia(publicId, image.public_id); setNotice('Image deleted.'); await load() } catch (caught) { setError(message(caught)) } finally { setBusy(null) } }
  async function move(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= images.length) return; const current = images[index]; const other = images[target]; setBusy(current.public_id); try { await Promise.all([updateProductMedia(publicId, current.public_id, { sort_order: other.sort_order }), updateProductMedia(publicId, other.public_id, { sort_order: current.sort_order })]); setNotice('Image order updated.'); await load() } catch (caught) { setError(message(caught)) } finally { setBusy(null) } }
  if (loading && !product) return <div className="p-12 text-center text-sm text-stone-500">Loading media…</div>
  if (!product) return <div className="rounded-lg bg-red-50 p-4 text-red-700">{error}</div>
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><PageHeader title={`${product.name} media`} description="Upload, order, and assign product and variant images." /><a href={`/products/${publicId}`} className="rounded-lg border px-4 py-2 text-sm">Product details</a></div>
    {error && <div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}{notice && <div className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}
    <form className="grid gap-5 rounded-xl border bg-white p-5 lg:grid-cols-[240px_1fr]" onSubmit={submit}><div className="grid aspect-square place-items-center overflow-hidden rounded-lg border border-dashed bg-stone-50">{preview ? <img src={preview} alt="Upload preview" className="h-full w-full object-cover" /> : <span className="p-4 text-center text-sm text-stone-500">Select JPG, PNG, or WebP up to 5 MB</span>}</div><div><h2 className="font-semibold">Upload image</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><input required className={control} type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => selectFile(event.target.files?.[0] ?? null)} /><input className={control} placeholder="Alt text" value={upload.alt_text} onChange={(event) => setUpload({ ...upload, alt_text: event.target.value })} /><select className={control} value={upload.variant_public_id} onChange={(event) => setUpload({ ...upload, variant_public_id: event.target.value })}><option value="">Product image</option>{product.variants?.map((variant) => <option key={variant.public_id} value={variant.public_id}>{variant.title ?? variant.sku}</option>)}</select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={upload.is_primary} onChange={(event) => setUpload({ ...upload, is_primary: event.target.checked })} />Set as primary in this scope</label></div>{progress !== null && <div className="mt-4"><div className="h-2 overflow-hidden rounded bg-stone-200"><div className="h-full bg-emerald-600" style={{ width: `${progress}%` }} /></div><p className="mt-1 text-xs text-stone-500">Uploading {progress}%</p></div>}<button disabled={!file || progress !== null} className="mt-4 rounded-lg bg-stone-900 px-4 py-2 text-sm text-white disabled:opacity-50">Upload image</button></div></form>
    <section><div className="flex items-center justify-between"><h2 className="font-semibold">Gallery</h2><span className="text-sm text-stone-500">{images.length} images</span></div>{!images.length ? <div className="mt-3 rounded-xl border border-dashed bg-white p-12 text-center text-sm text-stone-500">No images uploaded yet.</div> : <div className="mt-3 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{images.map((image, index) => <article key={image.public_id} className="overflow-hidden rounded-xl border bg-white"><div className="relative aspect-[4/3] bg-stone-100"><img className="h-full w-full object-cover" src={image.url} alt={image.alt_text ?? ''} />{image.is_primary && <span className="absolute left-2 top-2 rounded-full bg-stone-900 px-2 py-1 text-xs text-white">Primary</span>}</div><div className="space-y-3 p-4"><input className={control} defaultValue={image.alt_text ?? ''} placeholder="Alt text" onBlur={(event) => { if (event.target.value !== (image.alt_text ?? '')) void update(image, { alt_text: event.target.value || null }, 'Alt text updated.') }} /><select className={control} value={image.variant_public_id ?? ''} onChange={(event) => void update(image, { variant_public_id: event.target.value || null }, 'Image assignment updated.')}><option value="">Product image</option>{product.variants?.map((variant) => <option key={variant.public_id} value={variant.public_id}>{variant.title ?? variant.sku}</option>)}</select><div className="flex flex-wrap gap-2 text-sm"><button disabled={index === 0 || busy !== null} className="rounded border px-2 py-1 disabled:opacity-30" onClick={() => void move(index, -1)}>← Earlier</button><button disabled={index === images.length - 1 || busy !== null} className="rounded border px-2 py-1 disabled:opacity-30" onClick={() => void move(index, 1)}>Later →</button>{!image.is_primary && <button disabled={busy !== null} className="rounded border px-2 py-1" onClick={() => void update(image, { is_primary: true }, 'Primary image updated.')}>Set primary</button>}<button disabled={busy !== null} className="ml-auto text-red-700" onClick={() => void remove(image)}>Delete</button></div><p className="text-xs text-stone-500">{image.width}×{image.height} · {image.mime_type} · Order {image.sort_order}</p></div></article>)}</div>}</section>
  </div>
}
