import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { ApiError } from '../api/client'
import { listCategories } from '../categories/categoryService'
import type { Category } from '../categories/types'
import { PageHeader } from '../components/PageHeader'
import { deleteProduct, listProducts } from '../products/productService'
import type { Pagination, Product } from '../products/types'

const initial: Pagination = { total: 0, per_page: 20, current_page: 1, last_page: 1 }
const control = 'rounded-lg border border-stone-300 bg-white px-3 py-2 text-sm outline-none'
export function ProductsPage() {
  const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [pagination, setPagination] = useState(initial)
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null)
  const [searchInput, setSearchInput] = useState(''); const [search, setSearch] = useState(''); const [category, setCategory] = useState(''); const [status, setStatus] = useState(''); const [availability, setAvailability] = useState(''); const [sort, setSort] = useState('newest'); const [page, setPage] = useState(1); const [deleting, setDeleting] = useState<Product | null>(null)
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await listProducts({ page, per_page: 20, search, category, status, availability, sort }); setProducts(response.data); setPagination(response.meta.pagination) } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Products could not be loaded.') } finally { setLoading(false) } }, [page, search, category, status, availability, sort])
  // oxlint-disable-next-line react/set-state-in-effect
  useEffect(() => { void load() }, [load]); useEffect(() => { listCategories({ per_page: 100 }).then((r) => setCategories(r.data)).catch(() => undefined) }, [])
  function submitSearch(event: FormEvent) { event.preventDefault(); setPage(1); setSearch(searchInput.trim()) }
  async function remove() { if (!deleting) return; try { await deleteProduct(deleting.public_id); setNotice(`${deleting.name} was deleted.`); setDeleting(null); await load() } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Product could not be deleted.'); setDeleting(null) } }
  return <div className="space-y-6"><div className="flex items-end justify-between"><PageHeader title="Products" description="Manage product content, options, and sellable variants." /><a href="/products/create" className="rounded-lg bg-stone-900 px-4 py-2.5 text-sm font-medium text-white">Create product</a></div>
    {notice && <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}
    <div className="rounded-xl border border-stone-200 bg-white shadow-sm"><div className="grid gap-3 border-b p-4 lg:grid-cols-5"><form className="flex gap-2" onSubmit={submitSearch}><input className={`${control} min-w-0`} placeholder="Search products" value={searchInput} onChange={(e) => setSearchInput(e.target.value)} /><button className="rounded-lg border px-3 text-sm">Search</button></form><select className={control} value={category} onChange={(e) => { setCategory(e.target.value); setPage(1) }}><option value="">All categories</option>{categories.map((c) => <option key={c.public_id} value={c.slug}>{c.name}</option>)}</select><select className={control} value={status} onChange={(e) => { setStatus(e.target.value); setPage(1) }}><option value="">All statuses</option><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select><select className={control} value={availability} onChange={(e) => { setAvailability(e.target.value); setPage(1) }}><option value="">All availability</option><option value="available">Available</option><option value="unavailable">Unavailable</option></select><select className={control} value={sort} onChange={(e) => setSort(e.target.value)}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="name_asc">Name A–Z</option><option value="name_desc">Name Z–A</option><option value="price_asc">Price low–high</option><option value="price_desc">Price high–low</option></select></div>
      {error ? <div className="p-10 text-center text-sm text-red-700">{error}<button onClick={() => void load()} className="ml-2 underline">Try again</button></div> : loading ? <div className="p-12 text-center text-sm text-stone-500">Loading products…</div> : !products.length ? <div className="p-12 text-center"><p className="font-medium">No products found</p><p className="text-sm text-stone-500">Adjust filters or create the first product.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-stone-50 text-xs uppercase text-stone-500"><tr><th className="p-3">Product</th><th>Category</th><th>Status</th><th>Variants</th><th>Lowest price</th><th>Availability</th><th>Published</th><th>Actions</th></tr></thead><tbody className="divide-y">{products.map((product) => <tr key={product.public_id}><td className="p-3"><div className="flex items-center gap-3">{product.primary_image ? <img className="h-12 w-12 rounded object-cover" src={product.primary_image.url} alt={product.primary_image.alt_text ?? ''} /> : <div className="h-12 w-12 rounded bg-stone-100" />}<a className="font-medium hover:underline" href={`/products/${product.public_id}`}>{product.name}</a></div></td><td>{product.primary_category?.name ?? '—'}</td><td className="capitalize">{product.status}</td><td>{product.variant_count}</td><td>{product.lowest_price?.toLocaleString() ?? '—'} {product.currency}</td><td>{product.available ? 'Available' : 'Unavailable'}</td><td>{product.published_at ? new Date(product.published_at).toLocaleDateString() : '—'}</td><td><a className="font-medium" href={`/products/${product.public_id}/edit`}>Edit</a><button className="ml-3 text-red-700" onClick={() => setDeleting(product)}>Delete</button></td></tr>)}</tbody></table></div>}
      <div className="flex justify-between border-t p-3 text-sm"><span>{pagination.total} products · Page {pagination.current_page} of {pagination.last_page}</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded border px-3 py-1 disabled:opacity-40">Previous</button><button disabled={page >= pagination.last_page} onClick={() => setPage(page + 1)} className="rounded border px-3 py-1 disabled:opacity-40">Next</button></div></div></div>
    {deleting && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="w-full max-w-md rounded-xl bg-white p-6"><h2 className="text-lg font-semibold">Delete {deleting.name}?</h2><p className="mt-2 text-sm text-stone-600">This soft-deletes the product and its sellable variants.</p><div className="mt-5 flex justify-end gap-2"><button className="rounded border px-4 py-2" onClick={() => setDeleting(null)}>Cancel</button><button className="rounded bg-red-700 px-4 py-2 text-white" onClick={() => void remove()}>Delete product</button></div></div></div>}
  </div>
}
