import { useState, type FormEvent } from 'react'
import { ApiError } from '../api/client'
import { PageHeader } from '../components/PageHeader'
import { importTemplateUrl, previewProductImport, runProductImport } from '../imports/importService'
import type { ImportPreview, ImportResult } from '../imports/types'

const control = 'w-full rounded-lg border border-stone-300 bg-white px-3 py-2 text-sm'
export function ProductImportPage() {
  const [files, setFiles] = useState<{ products?: File; variants?: File; images?: File; media: File[] }>({ media: [] }); const [preview, setPreview] = useState<ImportPreview | null>(null); const [result, setResult] = useState<ImportResult | null>(null)
  const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<'preview' | 'import' | null>(null)
  function formData() { const form = new FormData(); if (files.products) form.append('products', files.products); if (files.variants) form.append('variants', files.variants); if (files.images) form.append('images', files.images); files.media.forEach((file) => form.append('media_files[]', file)); return form }
  async function validate(event: FormEvent) { event.preventDefault(); setBusy('preview'); setError(null); setResult(null); try { setPreview(await previewProductImport(formData())) } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Import preview failed.') } finally { setBusy(null) } }
  async function execute() { setBusy('import'); setError(null); try { const response = await runProductImport(formData()); setResult(response) } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Import failed.') } finally { setBusy(null) } }
  function downloadErrors() { if (!preview) return; const rows = [['product_reference', 'row', 'field', 'code', 'message'], ...preview.rows.flatMap((row) => row.errors.map((item) => [row.reference, String(row.row), item.field ?? '', item.code, item.message]))]; const csv = rows.map((row) => row.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = 'product-import-errors.csv'; link.click(); URL.revokeObjectURL(url) }
  return <div className="space-y-6"><PageHeader title="Bulk product import" description="Validate and create products, variants, and media from related CSV or XLSX files." />
    {error && <div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <section className="rounded-xl border bg-white p-5"><div className="flex flex-wrap gap-3 text-sm"><span className="font-medium">Templates:</span>{(['products', 'variants', 'images'] as const).map((type) => <a key={type} className="underline" href={importTemplateUrl(type)}>{type}.csv</a>)}</div><p className="mt-2 text-xs text-stone-500">Use the same product_reference across files. XLSX imports read the first worksheet.</p></section>
    <form className="rounded-xl border bg-white p-5" onSubmit={validate}><h2 className="font-semibold">Import files</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><label className="text-sm">Products CSV/XLSX *<input required className={`${control} mt-1`} type="file" accept=".csv,.xlsx" onChange={(event) => setFiles({ ...files, products: event.target.files?.[0] })} /></label><label className="text-sm">Variants CSV/XLSX *<input required className={`${control} mt-1`} type="file" accept=".csv,.xlsx" onChange={(event) => setFiles({ ...files, variants: event.target.files?.[0] })} /></label><label className="text-sm">Images CSV/XLSX<input className={`${control} mt-1`} type="file" accept=".csv,.xlsx" onChange={(event) => setFiles({ ...files, images: event.target.files?.[0] })} /></label><label className="text-sm md:col-span-3">Referenced image files<input className={`${control} mt-1`} type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={(event) => setFiles({ ...files, media: Array.from(event.target.files ?? []) })} /></label></div><button disabled={busy !== null} className="mt-4 rounded-lg bg-stone-900 px-4 py-2 text-sm text-white disabled:opacity-50">{busy === 'preview' ? 'Validating…' : 'Preview and validate'}</button></form>
    {preview && <section className="rounded-xl border bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="font-semibold">Validation preview</h2><p className="text-sm text-stone-500">{preview.summary.detected} products detected · <span className="text-emerald-700">{preview.summary.valid} valid</span> · <span className="text-red-700">{preview.summary.invalid} invalid</span></p></div><div className="flex gap-2">{preview.summary.invalid > 0 && <button className="rounded-lg border px-3 py-2 text-sm" onClick={downloadErrors}>Download error report</button>}<button disabled={preview.summary.valid === 0 || busy !== null || result !== null} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm text-white disabled:opacity-40" onClick={() => void execute()}>{busy === 'import' ? 'Importing…' : 'Import valid products'}</button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-stone-50 text-xs uppercase text-stone-500"><tr><th className="p-3">Reference</th><th>Product</th><th>Slug</th><th>Variants</th><th>Images</th><th>Validation</th></tr></thead><tbody className="divide-y">{preview.rows.map((row, index) => <tr key={`${row.reference}-${index}`}><td className="p-3">{row.reference || '—'}</td><td>{row.name || '—'}</td><td>{row.slug || '—'}</td><td>{row.variants}</td><td>{row.images}</td><td>{row.errors.length ? <ul className="py-2 text-xs text-red-700">{row.errors.map((item, errorIndex) => <li key={errorIndex}>{item.field ? `${item.field}: ` : ''}{item.message}</li>)}</ul> : <span className="text-emerald-700">Valid</span>}</td></tr>)}</tbody></table></div></section>}
    {result && <section className="rounded-xl border border-emerald-200 bg-emerald-50 p-5"><h2 className="font-semibold text-emerald-900">Import complete</h2><div className="mt-3 grid gap-3 sm:grid-cols-4"><div><span className="text-2xl font-semibold">{result.summary.created_products}</span><p className="text-sm">Products created</p></div><div><span className="text-2xl font-semibold">{result.summary.created_variants}</span><p className="text-sm">Variants created</p></div><div><span className="text-2xl font-semibold">{result.summary.imported_images}</span><p className="text-sm">Images imported</p></div><div><span className="text-2xl font-semibold">{result.summary.failed}</span><p className="text-sm">Products failed</p></div></div></section>}
  </div>
}
