import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { ApiError } from '../api/client'
import { listCategories } from '../categories/categoryService'
import type { Category } from '../categories/types'
import type { Product, ProductImage, ProductInput, ProductOption, ProductVariant } from './types'

const control = 'w-full rounded-lg border border-stone-300 bg-white px-3 py-2 text-sm outline-none focus:border-stone-600 focus:ring-2 focus:ring-stone-200'
const slug = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
const cartesian = (options: ProductOption[]): Record<string, string>[] => options.reduce<Record<string, string>[]>((rows, option) => rows.flatMap((row) => option.values.map((value) => ({ ...row, [option.code]: value.code }))), [{}])

export function ProductForm({ product, onSave }: { product?: Product; onSave: (input: ProductInput) => Promise<void> }) {
  const [categories, setCategories] = useState<Category[]>([])
  const [name, setName] = useState(product?.name ?? '')
  const [productSlug, setProductSlug] = useState(product?.slug ?? '')
  const [shortDescription, setShortDescription] = useState(product?.short_description ?? '')
  const [description, setDescription] = useState(product?.description ?? '')
  const [brand, setBrand] = useState(product?.brand ?? '')
  const [status, setStatus] = useState<Product['status']>(product?.status ?? 'draft')
  const [publishedAt, setPublishedAt] = useState(product?.published_at?.slice(0, 16) ?? '')
  const [selectedCategories, setSelectedCategories] = useState<string[]>(product?.categories?.map((c) => c.public_id) ?? [])
  const [primaryCategory, setPrimaryCategory] = useState(product?.categories?.find((c) => c.is_primary)?.public_id ?? '')
  const [images, setImages] = useState<ProductImage[]>(product?.images ?? [])
  const [options, setOptions] = useState<ProductOption[]>(product?.options ?? [])
  const [variants, setVariants] = useState<ProductVariant[]>(product?.variants ?? [])
  const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  const dirty = useMemo(() => JSON.stringify({ name, productSlug, shortDescription, description, brand, status, publishedAt, selectedCategories, primaryCategory, images, options, variants }) !== JSON.stringify({ name: product?.name ?? '', productSlug: product?.slug ?? '', shortDescription: product?.short_description ?? '', description: product?.description ?? '', brand: product?.brand ?? '', status: product?.status ?? 'draft', publishedAt: product?.published_at?.slice(0, 16) ?? '', selectedCategories: product?.categories?.map((c) => c.public_id) ?? [], primaryCategory: product?.categories?.find((c) => c.is_primary)?.public_id ?? '', images: product?.images ?? [], options: product?.options ?? [], variants: product?.variants ?? [] }), [name, productSlug, shortDescription, description, brand, status, publishedAt, selectedCategories, primaryCategory, images, options, variants, product])
  useEffect(() => { listCategories({ per_page: 100 }).then((r) => setCategories(r.data)).catch(() => setError('Categories could not be loaded.')) }, [])
  useEffect(() => { const listener = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault() }; window.addEventListener('beforeunload', listener); return () => window.removeEventListener('beforeunload', listener) }, [dirty])

  function addOption() { setOptions([...options, { name: '', code: '', sort_order: options.length, values: [] }]) }
  function updateOption(index: number, patch: Partial<ProductOption>) { setOptions(options.map((item, i) => i === index ? { ...item, ...patch } : item)) }
  function addValue(index: number) { updateOption(index, { values: [...options[index].values, { label: '', code: '', swatch_value: null, sort_order: options[index].values.length }] }) }
  function generateVariants() {
    if (options.some((option) => !option.code || option.values.length === 0)) { setError('Every option needs a code and at least one value.'); return }
    const existing = new Map(variants.map((variant) => [JSON.stringify(variant.option_values), variant]))
    setVariants(cartesian(options).map((selection, index) => existing.get(JSON.stringify(selection)) ?? { sku: '', title: options.map((o) => o.values.find((v) => v.code === selection[o.code])?.label).join(' / '), option_values: selection, price_amount: 0, compare_at_amount: null, currency: variants[0]?.currency ?? 'IDR', barcode: null, weight_grams: null, is_active: true, is_default: index === 0 }))
  }
  function updateVariant(index: number, patch: Partial<ProductVariant>) { setVariants(variants.map((item, i) => i === index ? { ...item, ...patch } : item)) }
  async function submit(event: FormEvent) {
    event.preventDefault(); setSaving(true); setError(null)
    if (selectedCategories.length && !primaryCategory) { setError('Select a primary category.'); setSaving(false); return }
    try {
      await onSave({ name, slug: productSlug || slug(name), short_description: shortDescription || null, description: description || null, brand: brand || null, status, published_at: publishedAt ? new Date(publishedAt).toISOString() : null, metadata: product?.metadata ?? null, categories: selectedCategories.map((id, index) => ({ category_public_id: id, is_primary: id === primaryCategory, sort_order: index })), images: images.map((image, index) => ({ ...image, url: undefined, variant_public_id: undefined, variant_sku: image.variant_sku ?? variants.find((variant) => variant.public_id === image.variant_public_id)?.sku ?? null, sort_order: index })), options, variants })
    } catch (reason) { setError(reason instanceof ApiError ? reason.errors.map((e) => `${e.field ? `${e.field}: ` : ''}${e.message}`).join(' ') : 'Product could not be saved.') } finally { setSaving(false) }
  }
  return <form onSubmit={submit} className="space-y-6">
    {error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <section className="grid gap-4 rounded-xl border border-stone-200 bg-white p-5 shadow-sm md:grid-cols-2"><h2 className="md:col-span-2 font-semibold">Product details</h2><label>Name<input required maxLength={200} className={control} value={name} onChange={(e) => { setName(e.target.value); if (!product) setProductSlug(slug(e.target.value)) }} /></label><label>Slug<input required className={control} value={productSlug} onChange={(e) => setProductSlug(slug(e.target.value))} /></label><label>Brand<input className={control} value={brand} onChange={(e) => setBrand(e.target.value)} /></label><label>Status<select className={control} value={status} onChange={(e) => setStatus(e.target.value as Product['status'])}><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select></label><label>Published at<input type="datetime-local" className={control} value={publishedAt} onChange={(e) => setPublishedAt(e.target.value)} /></label><label className="md:col-span-2">Short description<input maxLength={500} className={control} value={shortDescription} onChange={(e) => setShortDescription(e.target.value)} /></label><label className="md:col-span-2">Full description<textarea rows={5} className={control} value={description} onChange={(e) => setDescription(e.target.value)} /></label></section>
    <section className="rounded-xl border border-stone-200 bg-white p-5"><h2 className="font-semibold">Categories</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{categories.map((category) => <label key={category.public_id} className="flex items-center gap-2"><input type="checkbox" checked={selectedCategories.includes(category.public_id)} onChange={(e) => { const next = e.target.checked ? [...selectedCategories, category.public_id] : selectedCategories.filter((id) => id !== category.public_id); setSelectedCategories(next); if (!next.includes(primaryCategory)) setPrimaryCategory(next[0] ?? '') }} />{category.name}{selectedCategories.includes(category.public_id) && <input type="radio" name="primary" checked={primaryCategory === category.public_id} onChange={() => setPrimaryCategory(category.public_id)} aria-label={`Make ${category.name} primary`} />}</label>)}</div></section>
    <section className="rounded-xl border border-stone-200 bg-white p-5"><div className="flex justify-between"><h2 className="font-semibold">Image metadata</h2><button type="button" className="text-sm font-medium underline" onClick={() => setImages([...images, { path: '', alt_text: null, width: null, height: null, mime_type: null, sort_order: images.length, is_primary: images.length === 0, variant_sku: null }])}>Add image</button></div>{images.map((image, index) => <div key={index} className="mt-3 grid gap-2 rounded-lg border p-3 md:grid-cols-6"><input required placeholder="Path or URL" className={`${control} md:col-span-2`} value={image.path} onChange={(e) => setImages(images.map((item, i) => i === index ? { ...item, path: e.target.value } : item))} /><input placeholder="Alt text" className={`${control} md:col-span-2`} value={image.alt_text ?? ''} onChange={(e) => setImages(images.map((item, i) => i === index ? { ...item, alt_text: e.target.value || null } : item))} /><select className={control} value={image.variant_sku ?? variants.find((variant) => variant.public_id === image.variant_public_id)?.sku ?? ''} onChange={(e) => setImages(images.map((item, i) => i === index ? { ...item, variant_sku: e.target.value || null } : item))}><option value="">Product image</option>{variants.map((variant) => <option key={variant.public_id ?? variant.sku} value={variant.sku}>{variant.sku || variant.title}</option>)}</select><button type="button" className="text-sm text-red-700" onClick={() => setImages(images.filter((_, i) => i !== index))}>Remove</button><label className="flex items-center gap-2"><input type="radio" name={`primary-${image.variant_sku ?? 'product'}`} checked={image.is_primary} onChange={() => setImages(images.map((item, i) => ({ ...item, is_primary: i === index ? true : item.variant_sku === image.variant_sku ? false : item.is_primary })))} />Primary</label><input type="number" min="0" placeholder="Width" className={control} value={image.width ?? ''} onChange={(e) => setImages(images.map((item, i) => i === index ? { ...item, width: e.target.value ? Number(e.target.value) : null } : item))} /><input type="number" min="0" placeholder="Height" className={control} value={image.height ?? ''} onChange={(e) => setImages(images.map((item, i) => i === index ? { ...item, height: e.target.value ? Number(e.target.value) : null } : item))} /><input placeholder="MIME type" className={control} value={image.mime_type ?? ''} onChange={(e) => setImages(images.map((item, i) => i === index ? { ...item, mime_type: e.target.value || null } : item))} /></div>)}</section>
    <section className="rounded-xl border border-stone-200 bg-white p-5"><div className="flex justify-between"><h2 className="font-semibold">Options</h2><button type="button" onClick={addOption} className="text-sm font-medium underline">Add option</button></div>{options.map((option, index) => <div key={index} className="mt-4 rounded-lg border p-4"><div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input placeholder="Name (Color)" className={control} value={option.name} onChange={(e) => updateOption(index, { name: e.target.value, code: option.code || slug(e.target.value) })} /><input placeholder="Code" className={control} value={option.code} onChange={(e) => updateOption(index, { code: slug(e.target.value) })} /><button type="button" onClick={() => setOptions(options.filter((_, i) => i !== index).map((o, i) => ({ ...o, sort_order: i })))} className="text-sm text-red-700">Remove</button></div>{option.values.map((value, valueIndex) => <div key={valueIndex} className="mt-2 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input placeholder="Value label" className={control} value={value.label} onChange={(e) => { const values = option.values.map((v, i) => i === valueIndex ? { ...v, label: e.target.value, code: v.code || slug(e.target.value) } : v); updateOption(index, { values }) }} /><input placeholder="Value code" className={control} value={value.code} onChange={(e) => { const values = option.values.map((v, i) => i === valueIndex ? { ...v, code: slug(e.target.value) } : v); updateOption(index, { values }) }} /><button type="button" onClick={() => updateOption(index, { values: option.values.filter((_, i) => i !== valueIndex) })} className="text-sm text-red-700">Remove</button></div>)}<button type="button" onClick={() => addValue(index)} className="mt-2 text-sm font-medium underline">Add value</button></div>)}<button type="button" onClick={generateVariants} className="mt-4 rounded-lg bg-stone-800 px-4 py-2 text-sm text-white">Generate combinations</button></section>
    <section className="rounded-xl border border-stone-200 bg-white p-5"><h2 className="font-semibold">Variants</h2><div className="mt-3 space-y-3">{variants.map((variant, index) => <div key={JSON.stringify(variant.option_values)} className="grid gap-2 rounded-lg border p-3 md:grid-cols-7"><input placeholder="Title" className={`${control} md:col-span-2`} value={variant.title ?? ''} onChange={(e) => updateVariant(index, { title: e.target.value || null })} /><input required placeholder="SKU" className={control} value={variant.sku} onChange={(e) => updateVariant(index, { sku: e.target.value })} /><input placeholder="Barcode" className={control} value={variant.barcode ?? ''} onChange={(e) => updateVariant(index, { barcode: e.target.value || null })} /><input type="number" min="0" placeholder="Price" className={control} value={variant.price_amount} onChange={(e) => updateVariant(index, { price_amount: Number(e.target.value) })} /><input type="number" min="0" placeholder="Compare at" className={control} value={variant.compare_at_amount ?? ''} onChange={(e) => updateVariant(index, { compare_at_amount: e.target.value ? Number(e.target.value) : null })} /><input placeholder="Currency" maxLength={3} className={control} value={variant.currency} onChange={(e) => updateVariant(index, { currency: e.target.value.toUpperCase() })} /><input type="number" min="0" placeholder="Weight g" className={control} value={variant.weight_grams ?? ''} onChange={(e) => updateVariant(index, { weight_grams: e.target.value ? Number(e.target.value) : null })} /><label className="flex items-center gap-2"><input type="checkbox" checked={variant.is_active} onChange={(e) => updateVariant(index, { is_active: e.target.checked })} />Active</label><label className="flex items-center gap-2"><input type="radio" name="default" checked={variant.is_default} onChange={() => setVariants(variants.map((v, i) => ({ ...v, is_default: i === index, is_active: i === index ? true : v.is_active })))} />Default</label></div>)}</div></section>
    <div className="flex justify-end gap-3"><a href="/products" className="rounded-lg border px-4 py-2 text-sm">Cancel</a><button disabled={saving} className="rounded-lg bg-stone-900 px-5 py-2 text-sm font-medium text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save product'}</button></div>
  </form>
}
