"use client";

import { useEffect, useState } from "react";
import { AccountNav } from "@/components/account/AccountGuard";
import { AddressForm } from "@/components/account/AddressForm";
import { AccountApiError, createAddress, deleteAddress, getAddresses, updateAddress } from "@/services/account-api";
import type { Address, AddressInput } from "@/types/account";

export default function AddressesPage() {
  const [addresses, setAddresses] = useState<Address[]>([]); const [editing, setEditing] = useState<Address | null>(null); const [adding, setAdding] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { getAddresses().then(setAddresses).catch(() => setError('Unable to load your addresses.')); }, []);
  async function save(input: AddressInput) { setSaving(true); setError(''); try { const next = editing ? await updateAddress(editing.public_id, input) : await createAddress(input); setAddresses((current) => editing ? current.map((address) => address.public_id === next.public_id ? next : address) : [next, ...current]); setEditing(null); setAdding(false); } catch (caught) { setError(caught instanceof AccountApiError ? caught.errors.map((item) => item.message).join(' ') || caught.message : 'Unable to save this address.'); } finally { setSaving(false); } }
  async function remove(address: Address) { if (!window.confirm('Delete this address?')) return; try { await deleteAddress(address.public_id); setAddresses((current) => current.filter((item) => item.public_id !== address.public_id)); } catch { setError('Unable to delete this address.'); } }
  return <div className="page-shell section-space"><AccountNav /><div className="mt-14"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow text-plum">Delivery details</p><h1 className="editorial-title mt-3 text-5xl">Your addresses</h1></div><button onClick={() => { setAdding(true); setEditing(null); }} className="button-primary">Add address</button></div>{error && <p role="alert" className="mt-8 border border-rose/60 bg-ivory p-4 text-sm text-plum">{error}</p>}{(adding || editing) && <div className="mt-10"><AddressForm address={editing ?? undefined} saving={saving} onSubmit={save} onCancel={() => { setAdding(false); setEditing(null); }} /></div>}<div className="mt-10 grid gap-4 md:grid-cols-2">{addresses.map((address) => <article key={address.public_id} className="border border-line p-6"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow text-plum">{address.label || 'Address'}</p><h2 className="mt-2 text-lg font-medium">{address.recipient_name}</h2></div><div className="text-right text-[10px] font-semibold uppercase tracking-[.12em] text-muted">{address.is_default_shipping && <p>Default shipping</p>}{address.is_default_billing && <p>Default billing</p>}</div></div><p className="mt-4 text-sm leading-7 text-muted">{address.line1}{address.line2 && `, ${address.line2}`}<br />{address.city}{address.province && `, ${address.province}`} {address.postal_code}<br />{address.country_code}</p><div className="mt-6 flex gap-5 text-xs font-semibold uppercase tracking-[.14em]"><button onClick={() => { setEditing(address); setAdding(false); }} className="border-b border-ink">Edit</button><button onClick={() => void remove(address)} className="border-b border-ink">Delete</button></div></article>)}{!addresses.length && !adding && <p className="border border-dashed border-line p-8 text-sm text-muted">You have no saved addresses yet.</p>}</div></div></div>;
}